---
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/app"
    schedule:
      interval: "weekly"
      time: "17:00"
      day: "friday"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "17:00"
      day: "friday"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "17:00"
      day: "friday"
