name: Build and push on tags

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@5927c834f5b4fdf503fca6f4c7eccda82949e1ee # tag=v3.1.0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4fd812986e6c8c2a69e18311145f9371337f27d4 # tag=v3.4.0
      -
        name: Login to DockerHub
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # tag=v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@1ca370b3a9802c92e886402e0dd88098a2533b12 # tag=v1.1.1
        with:
          push: true
          tags: pointvy/pointvy:${{github.ref_name}}
          provenance: false             # temporary workaround, Cloud Run doesn't support multi-arch images
