name: Build on PR

on:
  pull_request:
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # tag=v3.2.0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # tag=v3.6.1
      -
#        name: Login to DockerHub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      -
        name: Build and push
        uses: docker/build-push-action@16ebe778df0e7752d2cfcbd924afdbbd89c1a755 # tag=v1.1.1
        with:
          push: false
          tags: pointvy/pointvy:latest
          provenance: false             # temporary workaround, Cloud Run doesn't support multi-arch images
